# Generated by Django 4.2.3 on 2023-09-25 11:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("telegram_bot", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TelegramBot",
        ),
    ]
